### ISSUE TITLE
error: argument <subcommand>: invalid choice: u'volume-list'

### ISSUE THREAD

**Issue by btbars** [Nexenture/openstack-instances-backups#5]
hello,
i've got issue with your scripts, i'm using ubuntu zesty 64bits 
nova --version
7.1.0

when i try to launch the script:
./create_snapshot.sh daily 7 --dry-run

```
error: argument <subcommand>: invalid choice: u'volume-list'
...
error: argument <subcommand>: invalid choice: u'volume-snapshot-list'


```

**Comment by rcarlier33** [comment]
I modify the file
rename them in .sh
[count_volume_snapshots.txt](https://github.com/Nexenture/openstack-instances-backups/files/1246080/count_volume_snapshots.txt)
[create_snapshot.txt](https://github.com/Nexenture/openstack-instances-backups/files/1246081/create_snapshot.txt)

I'm not very good but i hope it's good for you

**Comment by rcarlier33** [comment]
i test, and it's ok for me.
I am using OVH public cloud and a debian9
You just have an error in the count_volume because i'm a big sheet in awk so the command
`if output=$(openstack volume snapshot list | awk -F'|' '/\|/ && !/ID/{system("echo "$5"__"$2"__"$3"")}' | sort -n); then`

don't properly return the array
